package main

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/GoCraft-MC/gocraft-abi/gcpkg"
)

// generateGo writes the provider's events as Go types.
//
// One file, because a plugin's whole event vocabulary is a handful of structs
// and splitting it would only make an author hunt. The types satisfy
// gocraft.CustomEvent, so the same file serves both ends: the plugin that
// defines these events emits them through it, and the plugin that subscribes
// receives them through it.
func generateGo(manifest gcpkg.Manifest, chosen names, pkg string) (map[string]string, error) {
	out := &lines{}
	out.add("// Code generated by gocraft-cli from the manifest of %s. DO NOT EDIT.", manifest.ID)
	out.add("//")
	out.add("// This is that plugin's own description of its events, not a copy kept in")
	out.add("// step by hand. Regenerate after it changes: the compiler then names what")
	out.add("// moved, which is the one thing a positional payload never can.")
	out.add("package %s", pkg)
	out.blank()
	out.add("import gocraft \"github.com/GoCraft-MC/gocraft-api-go\"")

	for _, record := range manifest.Records {
		name := chosen.records[record.Name]
		fields := fieldsOf(manifest, record.Fields)
		out.blank()
		out.add("// %s is the %s carried by an event of %s.", name, record.Name, manifest.ID)
		writeGoStruct(out, chosen, name, fields)
		out.blank()
		out.add("func (r %s) value() gocraft.Value {", name)
		writeGoEncode(out, chosen, fields, "r.")
		out.add("\treturn gocraft.List(")
		for _, field := range fields {
			out.add("\t\t%s,", goValueOf(chosen, field, "r."))
		}
		out.add("\t)")
		out.add("}")
		out.blank()
		out.add("func %sFrom(value gocraft.Value) (%s, bool) {", lowerFirst(name), name)
		out.add("\tvar record %s", name)
		out.add("\tif value.Kind != gocraft.ValueList || len(value.List) < %d {", len(fields))
		out.add("\t\treturn record, false")
		out.add("\t}")
		for index, field := range fields {
			writeGoDecode(out, chosen, field.Type, fmt.Sprintf("value.List[%d]", index),
				"record."+identifier(field.Name), 1)
		}
		out.add("\treturn record, true")
		out.add("}")
	}

	for _, event := range manifest.Provides {
		name := chosen.events[event.Type]
		fields := fieldsOf(manifest, event.Fields)
		out.blank()
		out.add("// %sType is the name %s publishes this event under.", name, manifest.ID)
		out.add("const %sType = %q", name, event.Type)
		out.blank()
		out.add("// %s is the %s event.", name, event.Type)
		if event.Cancellable {
			out.add("//")
			out.add("// Cancellable: a subscriber may refuse it through the control, and the")
			out.add("// emitter is expected to abandon what it announced.")
		}
		writeGoStruct(out, chosen, name, fields)
		out.blank()
		out.add("func (*%s) EventType() string { return %sType }", name, name)
		out.blank()
		out.add("func (e *%s) Fields() []gocraft.Value {", name)
		writeGoEncode(out, chosen, fields, "e.")
		out.add("\treturn []gocraft.Value{")
		for _, field := range fields {
			out.add("\t\t%s,", goValueOf(chosen, field, "e."))
		}
		out.add("\t}")
		out.add("}")
		writeGoSetFields(out, chosen, name, fields)
		writeGoSubscribe(out, chosen, name, fields)
	}

	if carriesAPlayer(manifest) {
		writeGoPlayerHelper(out)
	}
	// Formatted here rather than left to the author. Generated code that is not
	// gofmt clean is noticed, and a file that will not parse is a bug in this
	// emitter — reported as one, with the source, rather than written out for
	// somebody else to discover.
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return nil, fmt.Errorf("gocraft-cli produced Go it cannot parse: %w\n%s",
			err, out.String())
	}
	return map[string]string{"events.gen.go": string(formatted)}, nil
}

// lines is the smallest thing that keeps the emitters readable.
type lines struct{ out strings.Builder }

func (l *lines) add(format string, args ...any) {
	fmt.Fprintf(&l.out, format+"\n", args...)
}

func (l *lines) blank() { l.out.WriteString("\n") }

func (l *lines) String() string { return l.out.String() }

func writeGoStruct(out *lines, chosen names, name string, fields []resolved) {
	out.add("type %s struct {", name)
	for _, field := range fields {
		note := ""
		if !field.Mutable {
			note = " // read-only: the provider declares it immutable"
		}
		out.add("\t%s %s%s", identifier(field.Name), goType(chosen, field.Type), note)
	}
	out.add("}")
}

// writeGoEncode leaves a local behind for every list field, because a list
// needs a loop and the value literal below needs an expression.
func writeGoEncode(out *lines, chosen names, fields []resolved, receiver string) {
	for _, field := range fields {
		if !field.Type.List {
			continue
		}
		local := lowerFirst(identifier(field.Name)) + "Values"
		source := receiver + identifier(field.Name)
		element := gcpkg.FieldType{Element: field.Type.Element, Record: field.Type.Record}
		out.add("\t%s := make([]gocraft.Value, 0, len(%s))", local, source)
		out.add("\tfor _, item := range %s {", source)
		out.add("\t\t%s = append(%s, %s)", local, local, goEncode(chosen, element, "item"))
		out.add("\t}")
	}
}

// goValueOf is one field as an expression, using the local a list left behind.
func goValueOf(chosen names, field resolved, receiver string) string {
	if field.Type.List {
		return "gocraft.List(" + lowerFirst(identifier(field.Name)) + "Values...)"
	}
	return goEncode(chosen, field.Type, receiver+identifier(field.Name))
}

// goType is what the field holds, in Go.
func goType(chosen names, parsed gcpkg.FieldType) string {
	element := ""
	switch parsed.Element {
	case gcpkg.ScalarBool:
		element = "bool"
	case gcpkg.ScalarInt:
		element = "int64"
	case gcpkg.ScalarDouble:
		element = "float64"
	case gcpkg.ScalarString:
		element = "string"
	case gcpkg.ScalarBytes:
		element = "[]byte"
	case gcpkg.TypePlayerRef:
		element = "*gocraft.PlayerRef"
	default:
		element = chosen.records[parsed.Element]
	}
	if parsed.List {
		return "[]" + element
	}
	return element
}

// goEncode is one value, as an expression. Never a list: those need a loop.
func goEncode(chosen names, parsed gcpkg.FieldType, source string) string {
	switch parsed.Element {
	case gcpkg.ScalarBool:
		return "gocraft.Bool(" + source + ")"
	case gcpkg.ScalarInt:
		return "gocraft.Int64(" + source + ")"
	case gcpkg.ScalarDouble:
		return "gocraft.Double(" + source + ")"
	case gcpkg.ScalarString:
		return "gocraft.String(" + source + ")"
	case gcpkg.ScalarBytes:
		return "gocraft.Bytes(" + source + ")"
	case gcpkg.TypePlayerRef:
		return "playerValue(" + source + ")"
	default:
		return source + ".value()"
	}
}

// writeGoSetFields takes back what the subscribers changed.
//
// Only the mutable fields, exactly as the JVM codec does: the host refused any
// write to the others before this was ever called, and assigning them anyway
// would replace a value nobody touched with a decode of itself.
func writeGoSetFields(out *lines, chosen names, name string, fields []resolved) {
	out.blank()
	out.add("func (e *%s) SetFields(fields []gocraft.Value) error {", name)
	out.add("\tif len(fields) < %d {", len(fields))
	out.add("\t\treturn nil")
	out.add("\t}")
	for index, field := range fields {
		if !field.Mutable {
			continue
		}
		writeGoDecode(out, chosen, field.Type, fmt.Sprintf("fields[%d]", index),
			"e."+identifier(field.Name), 1)
	}
	out.add("\treturn nil")
	out.add("}")
}

// writeGoSubscribe is the typed registration a handler is written against.
//
// It reads the payload out of the dispatch rather than through SetFields,
// because that is where a PlayerRef can be bound: a handle read anywhere else
// has no dispatch to act through, and a subscriber handed one it cannot answer
// was handed an identity rather than a handle.
func writeGoSubscribe(out *lines, chosen names, name string, fields []resolved) {
	out.blank()
	out.add("// On%s registers a handler for %s events.", name, name)
	out.add("//")
	out.add("// What the handler changed travels back to the emitter, however deep it")
	out.add("// reached: one line of a purchase discounted sends that line, not the list")
	out.add("// it sits in. A field nobody touched sends nothing.")
	out.add("func On%s(events *gocraft.Events, handler func(*%s, gocraft.EventControl)) error {",
		name, name)
	out.add("\treturn events.OnCustom(%sType, func(dispatch *gocraft.CustomDispatch, "+
		"control gocraft.EventControl) {", name)
	out.add("\t\tvar event %s", name)
	for index, field := range fields {
		target := "event." + identifier(field.Name)
		if field.Type.Element == gcpkg.TypePlayerRef && !field.Type.List {
			out.add("\t\tif player, ok := dispatch.Player(%d); ok {", index)
			out.add("\t\t\t%s = player", target)
			out.add("\t\t}")
			continue
		}
		out.add("\t\tif value, ok := dispatch.Field(%d); ok {", index)
		writeGoDecode(out, chosen, field.Type, "value", target, 3)
		out.add("\t\t}")
	}
	out.add("\t\thandler(&event, control)")
	// One call, and it reaches as deep as the change did. This used to compare
	// each mutable field at the top level, so a subscriber that changed a record
	// inside a list sent nothing at all — while the host would have taken the
	// write, a path of more than one index being answered by the field existing
	// rather than by its own mutability.
	out.add("\t\t_ = dispatch.Update(event.Fields())")
	out.add("\t})")
	out.add("}")
}

// writeGoDecode reads one value into a target.
//
// A shape that is not the declared one leaves the zero value, silently and only
// here: it means the provider changed its event and this plugin was not
// regenerated, which is exactly what regenerating turns into a compile error.
func writeGoDecode(out *lines, chosen names, parsed gcpkg.FieldType,
	value, target string, depth int) {
	tab := strings.Repeat("\t", depth)
	if parsed.List {
		element := gcpkg.FieldType{Element: parsed.Element, Record: parsed.Record}
		out.add("%sfor _, item := range %s.List {", tab, value)
		out.add("%s\tvar element %s", tab, goType(chosen, element))
		writeGoDecode(out, chosen, element, "item", "element", depth+1)
		out.add("%s\t%s = append(%s, element)", tab, target, target)
		out.add("%s}", tab)
		return
	}
	switch parsed.Element {
	case gcpkg.ScalarBool:
		out.add("%s%s = %s.Bool", tab, target, value)
	case gcpkg.ScalarInt:
		out.add("%s%s = %s.Int64", tab, target, value)
	case gcpkg.ScalarDouble:
		out.add("%s%s = %s.Double", tab, target, value)
	case gcpkg.ScalarString:
		out.add("%s%s = %s.String", tab, target, value)
	case gcpkg.ScalarBytes:
		out.add("%s%s = %s.Bytes", tab, target, value)
	case gcpkg.TypePlayerRef:
		out.add("%s%s = playerFrom(%s)", tab, target, value)
	default:
		out.add("%sif decoded, ok := %sFrom(%s); ok {", tab,
			lowerFirst(chosen.records[parsed.Element]), value)
		out.add("%s\t%s = decoded", tab, target)
		out.add("%s}", tab)
	}
}

func carriesAPlayer(manifest gcpkg.Manifest) bool {
	lists := [][]gcpkg.EventField{}
	for _, record := range manifest.Records {
		lists = append(lists, record.Fields)
	}
	for _, event := range manifest.Provides {
		lists = append(lists, event.Fields)
	}
	for _, fields := range lists {
		for _, field := range fields {
			if parsed, ok := gcpkg.ParseFieldType(field.Type); ok &&
				parsed.Element == gcpkg.TypePlayerRef {
				return true
			}
		}
	}
	return false
}

// writeGoPlayerHelper writes the PlayerRef shape the host reads back.
//
// Unbound on the way in, deliberately: a handle read outside a dispatch has
// nothing to act through. The subscribe helper reads the event's own player
// from the dispatch instead, which is where one can be answered.
func writeGoPlayerHelper(out *lines) {
	out.blank()
	out.add("func playerValue(player *gocraft.PlayerRef) gocraft.Value {")
	out.add("\tif player == nil {")
	out.add("\t\treturn gocraft.List()")
	out.add("\t}")
	out.add("\treturn gocraft.List(gocraft.Bytes(player.UUID[:]),")
	out.add("\t\tgocraft.String(player.Username), gocraft.String(player.Edition))")
	out.add("}")
	out.blank()
	out.add("func playerFrom(value gocraft.Value) *gocraft.PlayerRef {")
	out.add("\tif value.Kind != gocraft.ValueList || len(value.List) < 3 {")
	out.add("\t\treturn nil")
	out.add("\t}")
	out.add("\tplayer := &gocraft.PlayerRef{Username: value.List[1].String,")
	out.add("\t\tEdition: value.List[2].String}")
	out.add("\tcopy(player.UUID[:], value.List[0].Bytes)")
	out.add("\treturn player")
	out.add("}")
}
