package main

import (
	"fmt"
	"strings"

	"github.com/GoCraft-MC/gocraft-abi/gcpkg"
)

// generateJava writes the provider's events as Java classes and their codecs.
//
// Four files per event and record rather than one, because Java puts one public
// class per file and the runtime resolves a codec by appending Layout to the
// event's own name. The codec is written here rather than left to gocraft-apt:
// the layout is already known, and asking a subscriber to annotate a class it
// did not write would be asking it to describe the event a second time.
func generateJava(manifest gcpkg.Manifest, chosen names, pkg string) (map[string]string, error) {
	files := map[string]string{}
	for _, record := range manifest.Records {
		name := chosen.records[record.Name]
		fields := fieldsOf(manifest, record.Fields)
		files[name+".java"] = javaValueClass(manifest, pkg, name, record.Name, fields)
		files[name+"Values.java"] = javaRecordCodec(chosen, pkg, name, fields)
	}
	for _, event := range manifest.Provides {
		name := chosen.events[event.Type]
		fields := fieldsOf(manifest, event.Fields)
		files[name+".java"] = javaValueClass(manifest, pkg, name, event.Type, fields)
		files[name+"Layout.java"] = javaEventCodec(chosen, pkg, name, event, fields)
	}
	return files, nil
}

func javaHeader(out *lines, manifest gcpkg.Manifest, pkg string) {
	out.add("package %s;", pkg)
	out.blank()
	out.add("// Code generated by gocraft-cli from the manifest of %s. DO NOT EDIT.",
		manifest.ID)
	out.add("//")
	out.add("// This is that plugin's own description of its events, not a copy kept in")
	out.add("// step by hand. Regenerate after it changes: the compiler then names what")
	out.add("// moved, which is the one thing a positional payload never can.")
}

// javaValueClass is the plain class a handler receives.
//
// No annotation: @PluginEvent is how an author declares an event they define,
// and a subscriber defines nothing. The codec beside it is generated from the
// same manifest, so there is nothing for a processor to derive.
func javaValueClass(manifest gcpkg.Manifest, pkg, name, declared string,
	fields []resolved) string {
	out := &lines{}
	javaHeader(out, manifest, pkg)
	out.add("//")
	out.add("// Source: %s", declared)
	out.add("public final class %s {", name)
	out.blank()
	for _, field := range fields {
		modifier := "private"
		if !field.Mutable {
			modifier = "private final"
		}
		out.add("    %s %s %s;", modifier, javaType(names{}, field.Type), field.Name)
	}
	out.blank()
	out.add("    public %s(%s) {", name, javaSignature(fields))
	for _, field := range fields {
		out.add("        this.%s = %s;", field.Name, field.Name)
	}
	out.add("    }")
	for _, field := range fields {
		out.blank()
		out.add("    public %s %s() {", javaType(names{}, field.Type), field.Name)
		out.add("        return %s;", field.Name)
		out.add("    }")
		if !field.Mutable {
			continue
		}
		out.blank()
		out.add("    public void %s(%s %s) {", javaSetter(field.Name),
			javaType(names{}, field.Type), field.Name)
		out.add("        this.%s = %s;", field.Name, field.Name)
		out.add("    }")
	}
	out.add("}")
	return out.String()
}

func javaSignature(fields []resolved) string {
	parts := make([]string, 0, len(fields))
	for _, field := range fields {
		parts = append(parts, javaType(names{}, field.Type)+" "+field.Name)
	}
	return strings.Join(parts, ", ")
}

func javaSetter(name string) string {
	return "set" + strings.ToUpper(name[:1]) + name[1:]
}

// javaType is what the field holds, in Java. The names map is unused for now
// and kept in the signature so a record naming another reads the same way here
// as it does in the Go emitter.
func javaType(_ names, parsed gcpkg.FieldType) string {
	element := ""
	switch parsed.Element {
	case gcpkg.ScalarBool:
		element = "boolean"
	case gcpkg.ScalarInt:
		element = "long"
	case gcpkg.ScalarDouble:
		element = "double"
	case gcpkg.ScalarString:
		element = "String"
	case gcpkg.ScalarBytes:
		element = "byte[]"
	case gcpkg.TypePlayerRef:
		element = "fr.gocraft.api.PlayerRef"
	default:
		element = lastSegment(parsed.Element)
	}
	if parsed.List {
		if element == "boolean" {
			element = "Boolean"
		} else if element == "long" {
			element = "Long"
		} else if element == "double" {
			element = "Double"
		}
		return "java.util.List<" + element + ">"
	}
	return element
}

// javaRecordCodec is the pair of static methods an event's codec calls, exactly
// the shape gocraft-apt writes for a record an author declared themselves.
func javaRecordCodec(chosen names, pkg, name string, fields []resolved) string {
	out := &lines{}
	out.add("package %s;", pkg)
	out.blank()
	out.add("import fr.gocraft.api.EffectSink;")
	out.add("import fr.gocraft.api.Value;")
	out.add("import java.util.List;")
	out.blank()
	out.add("// Code generated by gocraft-cli. DO NOT EDIT.")
	out.add("public final class %sValues {", name)
	out.blank()
	out.add("    private %sValues() {", name)
	out.add("    }")
	out.blank()
	out.add("    static Value encode(%s value) {", name)
	javaEncodeFields(out, chosen, fields, "value.", 2)
	out.add("        return new Value.List(List.of(")
	javaValueList(out, chosen, fields, "value.", 3)
	out.add("        ));")
	out.add("    }")
	out.blank()
	out.add("    static %s decode(Value value, EffectSink sink) {", name)
	out.add("        if (!(value instanceof Value.List(List<Value> fields))) {")
	out.add("            throw new IllegalArgumentException(\"%s is not a list\");", name)
	out.add("        }")
	javaDecodeFields(out, chosen, fields, name, 2)
	out.add("        return new %s(%s);", name, javaArguments(fields))
	out.add("    }")
	if fieldsCarryAPlayer(fields) {
		javaPlayerHelper(out)
	}
	out.add("}")
	return out.String()
}

// javaEventCodec implements CustomEvent, which is what the runtime resolves by
// name when a handler declares the class beside it.
func javaEventCodec(chosen names, pkg, name string, event gcpkg.EventDefinition,
	fields []resolved) string {
	out := &lines{}
	out.add("package %s;", pkg)
	out.blank()
	out.add("import fr.gocraft.api.CustomEvent;")
	out.add("import fr.gocraft.api.EffectSink;")
	out.add("import fr.gocraft.api.Value;")
	out.add("import java.util.List;")
	out.blank()
	out.add("// Code generated by gocraft-cli. DO NOT EDIT.")
	out.add("public final class %sLayout implements CustomEvent {", name)
	out.blank()
	out.add("    @Override")
	out.add("    public String eventType() {")
	out.add("        return %q;", event.Type)
	out.add("    }")
	out.blank()
	out.add("    @Override")
	out.add("    public boolean cancellable() {")
	out.add("        return %t;", event.Cancellable)
	out.add("    }")
	out.blank()
	out.add("    @Override")
	out.add("    public List<Value> fields(Object event) {")
	out.add("        %s target = (%s) event;", name, name)
	javaEncodeFields(out, chosen, fields, "target.", 2)
	out.add("        return List.of(")
	javaValueList(out, chosen, fields, "target.", 3)
	out.add("        );")
	out.add("    }")
	out.blank()
	out.add("    @Override")
	out.add("    public void setFields(Object event, List<Value> fields) {")
	if !anyMutable(fields) {
		out.add("        // Every field is read-only: the provider declares none of them mutable.")
	} else {
		out.add("        %s target = (%s) event;", name, name)
		for index, field := range fields {
			if !field.Mutable {
				continue
			}
			out.add("        try {")
			javaDecodeOne(out, chosen, field, index, name, 3)
			out.add("            target.%s(%s);", javaSetter(field.Name), field.Name)
			out.add("        } catch (RuntimeException ignored) {")
			out.add("        }")
		}
	}
	out.add("    }")
	out.blank()
	out.add("    @Override")
	out.add("    public Object create(List<Value> fields, EffectSink sink) {")
	out.add("        if (fields.size() < %d) {", len(fields))
	out.add("            throw new IllegalArgumentException(\"%s arrived with \" + fields.size()"+
		" + \" fields, its layout declares %d\");", event.Type, len(fields))
	out.add("        }")
	javaDecodeFields(out, chosen, fields, event.Type, 2)
	out.add("        return new %s(%s);", name, javaArguments(fields))
	out.add("    }")
	if fieldsCarryAPlayer(fields) {
		javaPlayerHelper(out)
	}
	out.add("}")
	return out.String()
}

func javaArguments(fields []resolved) string {
	parts := make([]string, 0, len(fields))
	for _, field := range fields {
		parts = append(parts, field.Name)
	}
	return strings.Join(parts, ", ")
}

func anyMutable(fields []resolved) bool {
	for _, field := range fields {
		if field.Mutable {
			return true
		}
	}
	return false
}

func fieldsCarryAPlayer(fields []resolved) bool {
	for _, field := range fields {
		if field.Type.Element == gcpkg.TypePlayerRef {
			return true
		}
	}
	return false
}

// javaEncodeFields leaves a local behind for every list, which the value list
// below then names.
func javaEncodeFields(out *lines, chosen names, fields []resolved, receiver string, depth int) {
	tab := strings.Repeat("    ", depth)
	for _, field := range fields {
		if !field.Type.List {
			continue
		}
		local := field.Name + "Values"
		element := gcpkg.FieldType{Element: field.Type.Element, Record: field.Type.Record}
		out.add("%sjava.util.List<Value> %s = new java.util.ArrayList<>();", tab, local)
		out.add("%sfor (%s item : %s%s()) {", tab, javaType(chosen, element), receiver, field.Name)
		out.add("%s    %s.add(%s);", tab, local, javaEncode(chosen, element, "item"))
		out.add("%s}", tab)
	}
}

func javaValueList(out *lines, chosen names, fields []resolved, receiver string, depth int) {
	tab := strings.Repeat("    ", depth)
	for index, field := range fields {
		comma := ","
		if index+1 == len(fields) {
			comma = ""
		}
		if field.Type.List {
			out.add("%snew Value.List(%sValues)%s", tab, field.Name, comma)
			continue
		}
		out.add("%s%s%s", tab, javaEncode(chosen, field.Type, receiver+field.Name+"()"), comma)
	}
}

func javaEncode(chosen names, parsed gcpkg.FieldType, source string) string {
	switch parsed.Element {
	case gcpkg.ScalarBool:
		return "new Value.Bool(" + source + ")"
	case gcpkg.ScalarInt:
		return "new Value.Int(" + source + ")"
	case gcpkg.ScalarDouble:
		return "new Value.Decimal(" + source + ")"
	case gcpkg.ScalarString:
		return "new Value.Text(" + source + ")"
	case gcpkg.ScalarBytes:
		return "new Value.Bytes(" + source + ")"
	case gcpkg.TypePlayerRef:
		return "playerValue(" + source + ")"
	default:
		return lastSegment(parsed.Element) + "Values.encode(" + source + ")"
	}
}

func javaDecodeFields(out *lines, chosen names, fields []resolved, where string, depth int) {
	for index, field := range fields {
		javaDecodeOne(out, chosen, field, index, where, depth)
	}
}

// javaDecodeOne reads one field into a local named after it.
func javaDecodeOne(out *lines, chosen names, field resolved, index int, where string, depth int) {
	tab := strings.Repeat("    ", depth)
	value := fmt.Sprintf("fields.get(%d)", index)
	if field.Type.List {
		element := gcpkg.FieldType{Element: field.Type.Element, Record: field.Type.Record}
		raw := field.Name + "Raw"
		out.add("%sif (!(%s instanceof Value.List(List<Value> %s))) {", tab, value, raw)
		out.add("%s    throw new IllegalArgumentException(\"field %d of %s is not a list\");",
			tab, index, where)
		out.add("%s}", tab)
		out.add("%s%s %s = new java.util.ArrayList<>();", tab, javaType(chosen, field.Type),
			field.Name)
		out.add("%sfor (Value item : %s) {", tab, raw)
		javaDecodeValue(out, chosen, element, "item", field.Name+"Element",
			fmt.Sprintf("an element of field %d of %s", index, where), depth+1)
		out.add("%s    %s.add(%sElement);", tab, field.Name, field.Name)
		out.add("%s}", tab)
		return
	}
	javaDecodeValue(out, chosen, field.Type, value, field.Name,
		fmt.Sprintf("field %d of %s", index, where), depth)
}

func javaDecodeValue(out *lines, chosen names, parsed gcpkg.FieldType,
	value, target, where string, depth int) {
	tab := strings.Repeat("    ", depth)
	switch parsed.Element {
	case gcpkg.TypePlayerRef:
		out.add("%sfr.gocraft.api.PlayerRef %s = fr.gocraft.api.PlayerRef.of(%s, sink);",
			tab, target, value)
	case gcpkg.ScalarBool, gcpkg.ScalarInt, gcpkg.ScalarDouble, gcpkg.ScalarString,
		gcpkg.ScalarBytes:
		record, carried := javaCarried(parsed.Element)
		raw := target + "Raw"
		out.add("%sif (!(%s instanceof Value.%s(%s %s))) {", tab, value, record, carried, raw)
		out.add("%s    throw new IllegalArgumentException(\"%s is not a %s\");",
			tab, where, parsed.Element)
		out.add("%s}", tab)
		out.add("%s%s %s = %s;", tab, carried, target, raw)
	default:
		out.add("%s%s %s = %sValues.decode(%s, sink);", tab, lastSegment(parsed.Element),
			target, lastSegment(parsed.Element), value)
	}
}

// javaCarried is the Value record for a scalar and the type it hands back.
func javaCarried(element string) (string, string) {
	switch element {
	case gcpkg.ScalarBool:
		return "Bool", "boolean"
	case gcpkg.ScalarInt:
		return "Int", "long"
	case gcpkg.ScalarDouble:
		return "Decimal", "double"
	case gcpkg.ScalarString:
		return "Text", "String"
	default:
		return "Bytes", "byte[]"
	}
}

// javaPlayerHelper writes the PlayerRef shape the host reads back, for the same
// reason gocraft-apt does: the API jar a plugin compiles against deliberately
// has no encoder, so that a plugin cannot reach the transport.
func javaPlayerHelper(out *lines) {
	out.blank()
	out.add("    private static Value playerValue(fr.gocraft.api.PlayerRef player) {")
	out.add("        java.nio.ByteBuffer uuid = java.nio.ByteBuffer.allocate(16);")
	out.add("        uuid.putLong(player.uuid().getMostSignificantBits());")
	out.add("        uuid.putLong(player.uuid().getLeastSignificantBits());")
	out.add("        return new Value.List(List.of(")
	out.add("                new Value.Bytes(uuid.array()),")
	out.add("                new Value.Text(player.username()),")
	out.add("                new Value.Text(switch (player.edition()) {")
	out.add("                    case JAVA -> \"java\";")
	out.add("                    case BEDROCK -> \"bedrock\";")
	out.add("                    case UNKNOWN -> \"\";")
	out.add("                })));")
	out.add("    }")
}
